import { useState } from 'react';
import './App.css';
import ParcelAnalyzer from './components/ParcelAnalyzer';
import AdminPanel from './components/AdminPanel';
import { DEFAULT_PRODUCTS } from './data/products';

const WIZARD_STEPS = ['Search Parcel', 'Select Buildings', 'Configure', 'Site Layout'];

function StepBar({ current }) {
  return (
    <div className="step-bar">
      {WIZARD_STEPS.map((label, i) => {
        const num    = i + 1;
        const active = num === current;
        const done   = num < current;
        return (
          <div key={num} className="step-bar-segment">
            <div className={`step-bar-item${active ? ' sbi-active' : ''}${done ? ' sbi-done' : ''}`}>
              <span className="step-bar-num">{done ? '✓' : num}</span>
              <span className="step-bar-label">{label}</span>
            </div>
            {i < WIZARD_STEPS.length - 1 && (
              <div className={`step-bar-connector${done ? ' sbc-done' : ''}`} />
            )}
          </div>
        );
      })}
    </div>
  );
}

function buildOverviewEmail(parcel, results) {
  if (!parcel) return { subject: '', body: '' };
  const fitting = results.filter((r) => r.fits);
  const subject = `Parcel Fit Overview — ${parcel.matchedAddress || parcel.displayAddress}`;
  const lines = [
    `PARCEL FIT ANALYSIS OVERVIEW`,
    ``,
    `Address:    ${parcel.matchedAddress || parcel.displayAddress}`,
    parcel.parcelId ? `Parcel ID:  ${parcel.parcelId}` : null,
    `Area:       ${parcel.sqft.toLocaleString()} sq ft  (${parcel.acres.toFixed(3)} ac)`,
    `Dimensions: ${parcel.frontage} ft wide × ${parcel.depth} ft deep`,
    parcel.county ? `County:     ${parcel.county}, ${parcel.state}` : null,
    ``,
    `FITTING PRODUCTS (${fitting.length})`,
    ``,
    ...fitting.map((p) =>
      `• ${p.name} (${p.type})\n  Footprint: ${p.footprintW}′ × ${p.footprintD}′  |  Max buildings: ${p.count}  |  Total units: ${p.totalUnits}  |  Est. price: ${p.priceRange}`
    ),
    ``,
    `Generated by Volumod Volumod Fit Engine`,
  ].filter((l) => l !== null);
  return { subject, body: lines.join('\n') };
}

function App() {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [isAdmin, setIsAdmin] = useState(false);
  const [products, setProducts] = useState(DEFAULT_PRODUCTS);
  const [wizardStep, setWizardStep] = useState(1);
  const [overviewParcel,  setOverviewParcel]  = useState(null);
  const [overviewResults, setOverviewResults] = useState([]);

  function handleDataUpdate(parcel, results) {
    setOverviewParcel(parcel);
    setOverviewResults(results);
  }

  function handleEmailOverview() {
    const { subject, body } = buildOverviewEmail(overviewParcel, overviewResults);
    window.location.href = `mailto:troy.desmond@outlook.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  }

  return (
    <div className={`app ${isCollapsed ? 'collapsed' : ''}`}>
      <aside className="sidebar">
        <div className="sidebar-header">
          {!isCollapsed && <span className="logo">DevSoft</span>}
          <button
            className="collapse-btn"
            onClick={() => setIsCollapsed(!isCollapsed)}
            aria-label="Toggle sidebar"
          >
            {isCollapsed ? '›' : '‹'}
          </button>
        </div>

        <nav className="nav">
          <button
            className={`nav-item ${!isAdmin ? 'active' : ''}`}
            onClick={() => setIsAdmin(false)}
            title={isCollapsed ? 'Parcel Fit' : ''}
          >
            <span className="nav-icon">⊞</span>
            {!isCollapsed && <span className="nav-label">Parcel Fit</span>}
          </button>
        </nav>
      </aside>

      <main className="main-content">
        <div className="top-bar">
          {!isAdmin && <StepBar current={wizardStep} />}
          <button
            className={`gear-btn ${isAdmin ? 'gear-active' : ''}`}
            onClick={() => setIsAdmin((a) => !a)}
            title={isAdmin ? 'Exit Admin Mode' : 'Admin Mode'}
          >
            ⚙
          </button>
        </div>


        {isAdmin ? (
          <div className="page page-wide">
            <h1 className="page-title page-title-soft">Admin Mode</h1>
            <AdminPanel products={products} setProducts={setProducts} />
          </div>
        ) : (
          <div className="page page-wide">
            <ParcelAnalyzer products={products} wizardStep={wizardStep} setWizardStep={setWizardStep} onDataUpdate={handleDataUpdate} onEmailOverview={handleEmailOverview} />
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
